### ISSUE TITLE
Script to train "cambridgeltl/mirror-roberta-base-sentence-drophead"

### ISSUE THREAD

**Issue by luffycodes** [cambridgeltl/mirror-bert#5]
Hello, what are the parameters used to train this model? Are those parameters same as in this [file](https://github.com/cambridgeltl/mirror-bert/blob/main/mirror_scripts/mirror_sentence_roberta_drophead.sh) ??

Is the above the correct file to train this model?

**Comment by hardyqr** [comment]
Hi, yes that is correct.
